### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/CivMenu#18]
@TealNerd 

[15:57:14 WARN]: [CivMenu] Task #32 for CivMenu v1.2.0 generated an exc[10/9097]
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
        at vg.civcraft.mc.civmenu.guides.UnloadDismissalsTask.unloadCache(Unload
DismissalsTask.java:39) ~[?:?]
        at vg.civcraft.mc.civmenu.guides.UnloadDismissalsTask.run(UnloadDismissalsTask.java:25) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHea
rtbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
22) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
53) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:556) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]

**Comment by TealNerd** [comment]
Uh that's weird, I didn't change anything with the unload task

**Comment by Maxopoly** [comment]
Yeah, this wasnt related to your latest change, it was already occuring before that.

**Comment by TealNerd** [comment]
#19

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/CivMenu/pull/19

**Comment by Maxopoly** [comment]
http://build.civcraft.co/job/CivMenu/46/console

Didn't build
