### ISSUE TITLE
Exception while unloading dismissal tasks

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/CivMenu#22]
2016-02-06 19:19:40 [WARN] [CivMenu] Task #47 for CivMenu v1.2.2 generated an exception
java.util.NoSuchElementException
        at java.util.concurrent.ConcurrentHashMap$KeyIterator.next(ConcurrentHashMap.java:3416) ~[?:1.8.0_66-internal]
        at java.util.concurrent.ConcurrentHashMap$KeyIterator.nextElement(ConcurrentHashMap.java:3423) ~[?:1.8.0_66-internal]
        at vg.civcraft.mc.civmenu.guides.UnloadDismissalsTask.unloadCache(UnloadDismissalsTask.java:42) ~[?:?]
        at vg.civcraft.mc.civmenu.guides.UnloadDismissalsTask.run(UnloadDismissalsTask.java:26) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]

@TealNerd

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/CivMenu/commit/d3b1fac8bd51f5efde45b084e59b448ea3fb59d4
